[package]
name = "yelling-middleware"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
bytes = "1.12.1"
futures = "0.3.33"
spin-sdk = { git = "https://github.com/spinframework/spin-rust-sdk", branch = "main", default-features = false, features = ["http", "http-middleware"] }

[workspace]
