[package]
name = "spin-factor-outbound-networking"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
ip_network = "0.4.1"
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
serde = { workspace = true }
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }
spin-factors = { path = "../factors" }
spin-app = { path = "../app" }
spin-manifest = { path = "../manifest" }
spin-outbound-networking-config = { path = "../outbound-networking-config" }
spin-serde = { path = "../serde" }
tracing = { workspace = true }
url = { workspace = true }
webpki-roots = "0.26"

[dev-dependencies]
spin-factors-test = { path = "../factors-test" }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
toml = { workspace = true }
wasmtime-wasi = { workspace = true }

[features]
default = ["spin-cli"]
# Includes the runtime configuration handling used by the Spin CLI
spin-cli = []
[lints]
workspace = true
