//! This code works around incompatibilities between Clap 4 and `spin up`'s
//! messy trigger argument handling.
//!
//! It preprocesses the argument strings, splitting off those arguments
//! recognized by `spin up` itself by introspecting the arguments generated by
//! `UpCommandInner`'s `#[derive(Parser)]`.

use std::{
    collections::HashMap,
    ffi::{OsStr, OsString},
};

use clap::{ArgAction, Args, Command, CommandFactory, Parser};

use super::{UpCommand, UpCommandInner};

/// Determine how many values an argument consumes.
fn arg_num_vals(arg: &clap::Arg) -> usize {
    if let Some(num_args) = arg.get_num_args() {
        num_args.min_values()
    } else {
        // Derive-generated args may not set num_args explicitly;
        // infer from the action type.
        match arg.get_action() {
            ArgAction::Set | ArgAction::Append => 1,
            _ => 0,
        }
    }
}

/// Lookup tables mapping flag names to their argument definitions.
///
/// Used to identify which flags belong to `UpCommandInner` vs. trigger-specific
/// flags that should be passed through untouched.
struct FlagIndex<'a> {
    long: HashMap<&'a str, &'a clap::Arg>,
    short: HashMap<char, &'a clap::Arg>,
}

impl<'a> FlagIndex<'a> {
    fn from_command(cmd: &'a clap::Command) -> Self {
        let mut long = HashMap::new();
        let mut short = HashMap::new();
        for arg in cmd.get_arguments() {
            for name in arg
                .get_long()
                .into_iter()
                .chain(arg.get_all_aliases().unwrap_or_default())
            {
                long.insert(name, arg);
            }
            for ch in arg
                .get_short()
                .into_iter()
                .chain(arg.get_all_short_aliases().unwrap_or_default())
            {
                short.insert(ch, arg);
            }
        }
        Self { long, short }
    }
}

/// Consume the next `n` raw values from the cursor and append them to `dest`.
fn take_values(
    dest: &mut Vec<OsString>,
    raw_args: &clap_lex::RawArgs,
    cursor: &mut clap_lex::ArgCursor,
    n: usize,
) {
    for _ in 0..n {
        dest.extend(raw_args.next_os(cursor).map(ToOwned::to_owned));
    }
}

/// Split raw arguments into those recognized by `UpCommandInner` ("up args")
/// and everything else ("trigger args").
///
/// Unrecognized arguments are kept as trigger args so that each trigger's
/// own parser can handle them. If something truly invalid slips through,
/// the later `try_parse_from` call will produce a clear clap error.
fn split_args(flags: &FlagIndex, raw_args: clap_lex::RawArgs) -> (Vec<OsString>, Vec<OsString>) {
    let mut up_args: Vec<OsString> = vec!["spin up".into()];
    let mut trigger_args: Vec<OsString> = vec![];
    let mut cursor = raw_args.cursor();

    while let Some(parsed) = raw_args.next(&mut cursor) {
        if let Some((Ok(long), eq_value)) = parsed.to_long() {
            classify_long_flag(
                long,
                eq_value,
                &parsed,
                flags,
                &raw_args,
                &mut cursor,
                &mut up_args,
                &mut trigger_args,
            );
        } else if let Some(shorts) = parsed.to_short() {
            classify_short_flags(
                shorts,
                flags,
                &raw_args,
                &mut cursor,
                &mut up_args,
                &mut trigger_args,
            );
        } else {
            // Not a flag — UpCommandInner has no positional args, so this
            // belongs to a trigger.
            trigger_args.push(parsed.to_value_os().into());
        }
    }

    (up_args, trigger_args)
}

/// Route a `--long` flag (and its value(s)) to either up_args or trigger_args.
#[allow(clippy::too_many_arguments)]
fn classify_long_flag(
    long: &str,
    eq_value: Option<&OsStr>,
    parsed: &clap_lex::ParsedArg<'_>,
    flags: &FlagIndex,
    raw_args: &clap_lex::RawArgs,
    cursor: &mut clap_lex::ArgCursor,
    up_args: &mut Vec<OsString>,
    trigger_args: &mut Vec<OsString>,
) {
    let Some(arg) = flags.long.get(long) else {
        trigger_args.push(parsed.to_value_os().into());
        return;
    };

    up_args.push(parsed.to_value_os().to_os_string());

    // Determine how many trailing values to consume. If the value was
    // provided inline (e.g. `--key=value`), one has already been consumed.
    let mut remaining = arg_num_vals(arg);
    if remaining > 0 && eq_value.is_some() {
        remaining -= 1;
    }
    take_values(up_args, raw_args, cursor, remaining);
}

/// Route each flag in a short-flag cluster (e.g. `-abc`) to up_args or
/// trigger_args. Clap allows stacking, so `-abc` is equivalent to `-a -b -c`.
fn classify_short_flags(
    shorts: clap_lex::ShortFlags<'_>,
    flags: &FlagIndex,
    raw_args: &clap_lex::RawArgs,
    cursor: &mut clap_lex::ArgCursor,
    up_args: &mut Vec<OsString>,
    trigger_args: &mut Vec<OsString>,
) {
    for short_res in shorts {
        match short_res {
            Ok(ch) if flags.short.contains_key(&ch) => {
                up_args.push(format!("-{ch}").into());
                let remaining = arg_num_vals(flags.short[&ch]);
                take_values(up_args, raw_args, cursor, remaining);
            }
            Ok(ch) => {
                trigger_args.push(format!("-{ch}").into());
            }
            Err(invalid) => {
                trigger_args.push(OsString::from_iter([OsStr::new("-"), invalid]));
            }
        }
    }
}

impl Args for UpCommand {
    fn augment_args(cmd: clap::Command) -> clap::Command {
        // The FromArgMatches impl below depends on some restrictions on
        // UpCommandInner, which we assert here to prevent bugs
        for arg in UpCommandInner::command().get_arguments() {
            assert!(
                !arg.is_positional(),
                "UpCommandInner cannot use positional arg {arg}"
            );
            let num_vals = arg_num_vals(arg);
            let max_vals = arg.get_num_args().map_or(num_vals, |na| na.max_values());
            assert!(
                num_vals == max_vals,
                "UpCommandInner cannot use args with variable number of values"
            );
        }

        // Grab all arguments for later parsing
        cmd.disable_help_flag(true).arg(
            clap::Arg::new("args")
                .action(clap::ArgAction::Append)
                .allow_hyphen_values(true),
        )
    }

    fn augment_args_for_update(_: clap::Command) -> clap::Command {
        unimplemented!("UpCommand cannot be flattened")
    }
}

impl clap::FromArgMatches for UpCommand {
    fn from_arg_matches(matches: &clap::ArgMatches) -> std::result::Result<Self, clap::Error> {
        let cmd = UpCommandInner::command();
        let flags = FlagIndex::from_command(&cmd);

        let raw_args = clap_lex::RawArgs::new(matches.get_raw("args").into_iter().flatten());
        let (up_args, trigger_args) = split_args(&flags, raw_args);

        let mut inner = UpCommandInner::try_parse_from(up_args)?;
        inner.trigger_args = trigger_args;
        Ok(Self(inner))
    }

    fn update_from_arg_matches(
        &mut self,
        _: &clap::ArgMatches,
    ) -> std::result::Result<(), clap::Error> {
        unimplemented!("UpCommand cannot be flattened")
    }
}

impl Parser for UpCommand {}

impl CommandFactory for UpCommand {
    fn command() -> clap::Command {
        Self::augment_args(Command::default())
    }

    fn command_for_update() -> clap::Command {
        unimplemented!("UpCommand cannot be flattened")
    }
}
