[package]
name = "spin-loader"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
path-absolutize = { workspace = true, features = ["use_unix_paths_on_wasm"] }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
spin-common = { path = "../common" }
spin-expressions = { path = "../expressions" }
spin-app = { path = "../app" }
spin-manifest = { path = "../manifest" }
spin-outbound-networking-config = { path = "../outbound-networking-config" }
spin-serde = { path = "../serde" }
tempfile = { workspace = true }
terminal = { path = "../terminal" }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
wasm-pkg-client = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
ui-testing = { path = "../ui-testing" }

[features]
default = ["async-io"]
async-io = ["tokio/fs"]

[[test]]
name = "ui"
path = "tests/ui.rs"
harness = false
