manifest_version = "1"
id = "http-cpp"
description = "HTTP request handler using WASI P2, C++ and the WASI-SDK toolchain"
tags = ["http", "cpp", "c++"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
