[package]
name = "timer-app-example"
authors = ["Spin Framework Contributors"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.46.0"

[workspace]
